In [32]:
import numpy as np

def ewma(series, alpha):
    y = np.zeros_like(series)
    y[0] = series[0]
    for i in range(1, len(series)):
        y[i] = alpha * series[i] + (1 - alpha) * y[i-1]
    return y

In [33]:
alpha = 0.07995558537067671
series = np.ones(10) * 10

ewma(series, alpha)

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [34]:
series = np.arange(20) * 10

ewma(series, alpha)

array([ 0,  0,  1,  3,  5,  8, 12, 16, 21, 26, 31, 37, 43, 49, 56, 63, 70,
       77, 85, 93])

In [42]:
series = np.ones(300, dtype=np.float64) * 10
series[0:5] = 0
series[90:180] = 0

ewma(series, alpha)

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 7.99555854e-01, 1.53518275e+00, 2.21199217e+00,
       2.83468689e+00, 3.40759370e+00, 3.93469340e+00, 4.41964854e+00,
       4.86582881e+00, 5.27633447e+00, 5.65401791e+00, 6.00150346e+00,
       6.32120559e+00, 6.61534575e+00, 6.88596776e+00, 7.13495203e+00,
       7.36402862e+00, 7.57478925e+00, 7.76869840e+00, 7.94710342e+00,
       8.11124397e+00, 8.26226057e+00, 8.40120254e+00, 8.52903533e+00,
       8.64664717e+00, 8.75485529e+00, 8.85441156e+00, 8.94600775e+00,
       9.03028032e+00, 9.10781483e+00, 9.17915001e+00, 9.24478155e+00,
       9.30516549e+00, 9.36072139e+00, 9.41183528e+00, 9.45886234e+00,
       9.50212932e+00, 9.54193686e+00, 9.57856156e+00, 9.61225792e+00,
       9.64326007e+00, 9.67178342e+00, 9.69802617e+00, 9.72217066e+00,
       9.74438467e+00, 9.76482254e+00, 9.78362629e+00, 9.80092658e+00,
       9.81684361e+00, 9.83148799e+00, 9.84496146e+00, 9.85735766e+00,
      